extend type Query {
  """
  ✨ Look up a single `Appointment` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  appointment(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Appointment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Appointment_FirstRow
  ): Appointment @fdc_generated(from: "Appointment", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Medication` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  medication(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Medication_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Medication_FirstRow
  ): Medication @fdc_generated(from: "Medication", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Pet` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  pet(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Pet_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Pet_FirstRow
  ): Pet @fdc_generated(from: "Pet", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Vaccination` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  vaccination(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Vaccination_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Vaccination_FirstRow
  ): Vaccination @fdc_generated(from: "Vaccination", purpose: QUERY_SINGLE)
  """
  ✨ List `Appointment` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  appointments(
    """
    Filter condition to narrow down the query results.
    """
    where: Appointment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Appointment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Appointment_Having
  ): [Appointment!]! @fdc_generated(from: "Appointment", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Medication` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  medications(
    """
    Filter condition to narrow down the query results.
    """
    where: Medication_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Medication_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Medication_Having
  ): [Medication!]! @fdc_generated(from: "Medication", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Pet` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  pets(
    """
    Filter condition to narrow down the query results.
    """
    where: Pet_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Pet_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Pet_Having
  ): [Pet!]! @fdc_generated(from: "Pet", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Vaccination` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  vaccinations(
    """
    Filter condition to narrow down the query results.
    """
    where: Vaccination_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Vaccination_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Vaccination_Having
  ): [Vaccination!]! @fdc_generated(from: "Vaccination", purpose: QUERY_MULTIPLE)
}
