// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnTE4IkZFTT1zmk_asIbSbtXExxWtpUy4',
    appId: '1:17187771784:ios:1c4e2b8274442b40c6d63d',
    messagingSenderId: '17187771784',
    projectId: 'marketpet-app',
    storageBucket: 'marketpet-app.firebasestorage.app',
    iosBundleId: 'com.example.appFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ5K75NCtm4JyLwC4J5WlD-xq5mjteXUs',
    appId: '1:17187771784:web:9926a157cf9e0f80c6d63d',
    messagingSenderId: '17187771784',
    projectId: 'marketpet-app',
    authDomain: 'marketpet-app.firebaseapp.com',
    storageBucket: 'marketpet-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ5K75NCtm4JyLwC4J5WlD-xq5mjteXUs',
    appId: '1:17187771784:web:9926a157cf9e0f80c6d63d',
    messagingSenderId: '17187771784',
    projectId: 'marketpet-app',
    authDomain: 'marketpet-app.firebaseapp.com',
    storageBucket: 'marketpet-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnTE4IkZFTT1zmk_asIbSbtXExxWtpUy4',
    appId: '1:17187771784:ios:1c4e2b8274442b40c6d63d',
    messagingSenderId: '17187771784',
    projectId: 'marketpet-app',
    storageBucket: 'marketpet-app.firebasestorage.app',
    iosBundleId: 'com.example.appFlutter',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD51rA1rrXDM8h0sH3ciO1DEu-cK0xDQC4',
    appId: '1:17187771784:android:95d9b69b0e80084bc6d63d',
    messagingSenderId: '17187771784',
    projectId: 'marketpet-app',
    storageBucket: 'marketpet-app.firebasestorage.app',
  );

}